#! /bin/bash

require base
have_task || die "No task loaded"

find "$DEV_TASK_DIR/"{master,slave} \( -name '*.pyc' -o -name '*.rej' -o -name '*.orig' \) -exec rm \{} \;
rm -rf master/build master/dist
rm -rf slave/build slave/dist
