#! /bin/bash

require base
have_task || die "No task loaded"

if test -z "$VIRTUAL_ENV"; then
    echo "Activating sandbox"
    source "$DEV_TASK_DIR/sandbox/bin/activate"
fi

make -C master/docs VERSION=latest clean html
