#! /bin/bash

require base
have_task || die "No task loaded"

reset_basedir=true
test "$1" = "-k" && reset_basedir=false # k is for "keep"

if test -n "$1"; then
    MASTER_CONFIG="$PWD/$1"
fi

test -z "$MASTER_CONFIG" && die "Add MASTER_CONFIG to the task configuration or on the command line"

find "$DEV_TASK_DIR"/{master,slave} -name '*.pyc' -exec rm \{} \;
echo "Activating sandbox"
source "$DEV_TASK_DIR/sandbox/bin/activate"

PIDFILE="$VIRTUAL_ENV/master/twistd.pid"
BASEDIR="$VIRTUAL_ENV/master"

if [ -f "$PIDFILE" ]; then
    buildbot stop "$BASEDIR" || exit 1
fi

if $reset_basedir; then
    #(cd "$DEV_TASK_DIR/master"; python setup.py develop) || exit 1
    rm -rf "$BASEDIR"
    buildbot create-master "$BASEDIR" || exit 1
    # hack out the logfile rotation stuff
    sed -i -e 's/application.setComponent/#application.setComponent/' "$BASEDIR/buildbot.tac"
fi
cp "$MASTER_CONFIG" "$BASEDIR/master.cfg"

cd "$BASEDIR"
twistd --nodaemon --pidfile="$PIDFILE" --no_save -y "$BASEDIR/buildbot.tac" || exit 1
