#! /bin/bash

require base
have_task || die "No task loaded"

# pass the -b (debug) flag along
if [ "$1" = "-b" ]; then
    debug=-b
    shift
fi

find "$DEV_TASK_DIR/master/buildbot" "$DEV_TASK_DIR/slave/buildslave" -name '*.pyc' -exec rm \{} \;

if test -z "$1"; then
    TEST='buildbot.test buildslave.test'
else
    TEST="${@}"
fi

if test -z "$VIRTUAL_ENV"; then
    echo "Activating sandbox"
    source "$DEV_TASK_DIR/sandbox/bin/activate"
fi

rm -rf /tmp/trialtemp

echo "starting.."
trial $debug --reporter bwverbose --temp-directory /tmp/trialtemp ${TEST}
