#! /bin/bash

require base
have_task || die "No task loaded"

while true; do
    # pass the -b (debug) flag along
    if [ "$1" = "-b" ]; then
        debug=-b
        shift
        continue
    elif [ "$1" = "-m" ]; then
        export BUILDBOT_TEST_DB_URL=mysql+mysqldb://metabuildslave@knuth/metabuildslave
        shift
        continue
    elif [ "$1" = "-p" ]; then
        export BUILDBOT_TEST_DB_URL=postgresql+pg8000://metabuildslave@knuth/metabuildslave
        shift
        continue
    fi
    break
done

find "$DEV_TASK_DIR/master/buildbot" "$DEV_TASK_DIR/slave/buildslave" -name '*.pyc' -exec rm \{} \;

if test -z "$1"; then
    # use the text reporter for the whole suite (that much console scrolling is slow on laggy connections)
    reporter=text
    TEST='buildbot.test buildslave.test'
else
    # show all test names in a copy/pasteable fashion
    reporter=bwverbose
    TEST="${@}"
fi

if test -z "$VIRTUAL_ENV"; then
    echo "Activating sandbox"
    source "$DEV_TASK_DIR/sandbox/bin/activate"
fi

TMPDIR=/tmp/trialtemp
[ -d /A ] && TMPDIR=/A/trialtemp

rm -rf "${TMPDIR}"

echo "starting.."
trial $debug --reporter $reporter --temp-directory "${TMPDIR}" ${TEST}
