#! /bin/bash

require base color
have_task || die "No task loaded"

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" || die "not on a branch"
branch_name="${branch_name##refs/heads/}"
echo "validating branch: $branch_name"

# figure out what the old revision is
OLDREV="org/$branch_name"
echo "fetching from github.."
git fetch org || exit 1

find "$DEV_TASK_DIR/master/buildbot" "$DEV_TASK_DIR/slave/buildslave" -name '*.pyc' -exec rm \{} \;

if test -z "$VIRTUAL_ENV"; then
    echo "Activating sandbox"
    source "$DEV_TASK_DIR/sandbox/bin/activate"
fi

cd "${DEV_TASK_DIR}" || exit 1
if ./common/validate.sh $OLDREV; then
    git push org || exit 1
    git push || exit 1
fi
